version: "3.4"
services:
  zappa:
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "8000:8000"
    volumes:
      - .:/var/task
      - ~/.aws/:/root/.aws
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    environment:
      - DJANGO_SETTINGS_MODULE=zanebclark_website.settings-dev
#    command: [ "bash" ]